// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaa_3syvXQtp3tTaDRHxr4-vHx5tis5m8',
    appId: '1:139110918785:web:6bff8b4bb2c710bdf5fb80',
    messagingSenderId: '139110918785',
    projectId: 'hb-bm-205c9',
    authDomain: 'hb-bm-205c9.firebaseapp.com',
    storageBucket: 'hb-bm-205c9.firebasestorage.app',
    measurementId: 'G-1RNG0RP7DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLKgHt-YPb9K7gh33ElD-OpEI60HCfC4Y',
    appId: '1:139110918785:android:0d6cee5cd4665685f5fb80',
    messagingSenderId: '139110918785',
    projectId: 'hb-bm-205c9',
    storageBucket: 'hb-bm-205c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh4WEBYiGYtNiIqh8rsh9qwq-vdpAeJGU',
    appId: '1:139110918785:ios:5a01b77c1c6b5a18f5fb80',
    messagingSenderId: '139110918785',
    projectId: 'hb-bm-205c9',
    storageBucket: 'hb-bm-205c9.firebasestorage.app',
    iosBundleId: 'com.example.herzblatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh4WEBYiGYtNiIqh8rsh9qwq-vdpAeJGU',
    appId: '1:139110918785:ios:5a01b77c1c6b5a18f5fb80',
    messagingSenderId: '139110918785',
    projectId: 'hb-bm-205c9',
    storageBucket: 'hb-bm-205c9.firebasestorage.app',
    iosBundleId: 'com.example.herzblatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaa_3syvXQtp3tTaDRHxr4-vHx5tis5m8',
    appId: '1:139110918785:web:668e8a45047e9126f5fb80',
    messagingSenderId: '139110918785',
    projectId: 'hb-bm-205c9',
    authDomain: 'hb-bm-205c9.firebaseapp.com',
    storageBucket: 'hb-bm-205c9.firebasestorage.app',
    measurementId: 'G-CJW03Q0Z6X',
  );
}
